# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-09-22T11:27:16+00:00

from __future__ import annotations

from typing import List, Optional, Union

from fastapi import FastAPI, Path
from pydantic import conint

from .models import (
    BadRequestError,
    ClientRequest,
    ClientResponse,
    ConflictError,
    ForbiddenError,
    GatewayTimeoutError,
    HealthResponse,
    NotAuthorizedError,
    NotFoundError,
    RentalRequest,
    RentalResponse,
    ServiceUnavailableError,
)

app = FastAPI(
    title='API ArriendaPro',
    description='API REST para la gestión de arriendos y clientes.',
    version='1.0.0',
    servers=[
        {
            'url': 'http://localhost:8000',
            'description': 'Entorno local (Docker Compose)',
        }
    ],
)


@app.get('/health', response_model=HealthResponse, tags=['Health'])
def health_check() -> HealthResponse:
    """
    Estado del servicio
    """
    pass


@app.post(
    '/v1/clients',
    response_model=ClientResponse,
    status_code=201,
    responses={
        '400': {'model': BadRequestError},
        '401': {'model': NotAuthorizedError},
        '403': {'model': ForbiddenError},
        '409': {'model': ConflictError},
    },
    tags=['Clients'],
)
def create_client(
    body: ClientRequest,
) -> Union[
    ClientResponse, BadRequestError, NotAuthorizedError, ForbiddenError, ConflictError
]:
    """
    Crear un nuevo cliente
    """
    pass


@app.get(
    '/v1/clients',
    response_model=List[ClientResponse],
    responses={
        '400': {'model': BadRequestError},
        '401': {'model': NotAuthorizedError},
        '403': {'model': ForbiddenError},
    },
    tags=['Clients'],
)
def get_all_clients(
    limit: Optional[conint(ge=1, le=100)] = 20, offset: Optional[conint(ge=0)] = 0
) -> Union[List[ClientResponse], BadRequestError, NotAuthorizedError, ForbiddenError]:
    """
    Listar clientes
    """
    pass


@app.get(
    '/v1/clients/{clientId}',
    response_model=ClientResponse,
    responses={
        '400': {'model': BadRequestError},
        '401': {'model': NotAuthorizedError},
        '403': {'model': ForbiddenError},
        '404': {'model': NotFoundError},
    },
    tags=['Clients'],
)
def get_client_by_id(
    client_id: conint(ge=1) = Path(..., alias='clientId')
) -> Union[
    ClientResponse, BadRequestError, NotAuthorizedError, ForbiddenError, NotFoundError
]:
    """
    Obtener datos de un cliente
    """
    pass


@app.post(
    '/v1/rentals',
    response_model=RentalResponse,
    status_code=201,
    responses={
        '400': {'model': BadRequestError},
        '401': {'model': NotAuthorizedError},
        '403': {'model': ForbiddenError},
        '404': {'model': NotFoundError},
        '409': {'model': ConflictError},
        '503': {'model': ServiceUnavailableError},
        '504': {'model': GatewayTimeoutError},
    },
    tags=['Rentals'],
)
def create_rental(
    body: RentalRequest,
) -> Union[
    RentalResponse,
    BadRequestError,
    NotAuthorizedError,
    ForbiddenError,
    NotFoundError,
    ConflictError,
    ServiceUnavailableError,
    GatewayTimeoutError,
]:
    """
    Crear un nuevo arriendo
    """
    pass


@app.get(
    '/v1/rentals',
    response_model=List[RentalResponse],
    responses={
        '400': {'model': BadRequestError},
        '401': {'model': NotAuthorizedError},
        '403': {'model': ForbiddenError},
    },
    tags=['Rentals'],
)
def get_all_rentals(
    limit: Optional[conint(ge=1, le=100)] = 20, offset: Optional[conint(ge=0)] = 0
) -> Union[List[RentalResponse], BadRequestError, NotAuthorizedError, ForbiddenError]:
    """
    Listar arriendos
    """
    pass


@app.get(
    '/v1/rentals/{rentalId}',
    response_model=RentalResponse,
    responses={
        '400': {'model': BadRequestError},
        '401': {'model': NotAuthorizedError},
        '403': {'model': ForbiddenError},
        '404': {'model': NotFoundError},
    },
    tags=['Rentals'],
)
def get_rental_by_id(
    rental_id: conint(ge=1) = Path(..., alias='rentalId')
) -> Union[
    RentalResponse, BadRequestError, NotAuthorizedError, ForbiddenError, NotFoundError
]:
    """
    Obtener datos de un arriendo
    """
    pass


@app.post(
    '/v1/rentals/{rentalId}/cancel',
    response_model=RentalResponse,
    responses={
        '400': {'model': BadRequestError},
        '401': {'model': NotAuthorizedError},
        '403': {'model': ForbiddenError},
        '404': {'model': NotFoundError},
        '409': {'model': ConflictError},
        '503': {'model': ServiceUnavailableError},
        '504': {'model': GatewayTimeoutError},
    },
    tags=['Rentals'],
)
def cancel_rental(rental_id: conint(ge=1) = Path(..., alias='rentalId')) -> Union[
    RentalResponse,
    BadRequestError,
    NotAuthorizedError,
    ForbiddenError,
    NotFoundError,
    ConflictError,
    ServiceUnavailableError,
    GatewayTimeoutError,
]:
    """
    Cancelar un arriendo
    """
    pass


@app.post(
    '/v1/rentals/{rentalId}/return',
    response_model=RentalResponse,
    responses={
        '400': {'model': BadRequestError},
        '401': {'model': NotAuthorizedError},
        '403': {'model': ForbiddenError},
        '404': {'model': NotFoundError},
        '409': {'model': ConflictError},
        '503': {'model': ServiceUnavailableError},
        '504': {'model': GatewayTimeoutError},
    },
    tags=['Rentals'],
)
def return_rental(rental_id: conint(ge=1) = Path(..., alias='rentalId')) -> Union[
    RentalResponse,
    BadRequestError,
    NotAuthorizedError,
    ForbiddenError,
    NotFoundError,
    ConflictError,
    ServiceUnavailableError,
    GatewayTimeoutError,
]:
    """
    Retornar un arriendo
    """
    pass
