# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-09-21T13:38:17+00:00


from fastapi import FastAPI, Request, status
from fastapi.exceptions import RequestValidationError, HTTPException
from fastapi.responses import JSONResponse

from routers.v1 import rentals
from database import engine, Base
from routers.v1 import clients

from models import HealthResponse

Base.metadata.create_all(bind=engine)
    
app = FastAPI(
    title='API ArriendaPro',
    description='API REST para la gestión de arriendos y clientes.',
    version='1.0.0',
    servers=[
        {
            'url': 'http://localhost:8000',
            'description': 'Entorno local (Docker Compose)',
        }
    ],
)

@app.get('/health', response_model=HealthResponse, tags=['System'])
def health_check() -> HealthResponse:

    return HealthResponse(status="ok")