# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-09-21T13:38:17+00:00


from fastapi import FastAPI, Request, status
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

from app.routers.v1 import rentals, clients
from app.database import engine, Base

from app.models import HealthResponse

Base.metadata.create_all(bind=engine)
    
app = FastAPI(
    title='API ArriendaPro',
    description='API REST para la gestión de arriendos y clientes.',
    version='1.0.0',
    servers=[
        {
            'url': 'http://localhost:8000',
            'description': 'Entorno local (Docker Compose)',
        }
    ],
)

@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    first_err = exc.errors()[0]
    loc = ".".join([str(k) for k in first_err.get("loc", []) if k != "body"])
    return JSONResponse(
        status_code=status.HTTP_400_BAD_REQUEST,
        content={"code": "BAD_REQUEST", "message": f"Error en '{loc}': {first_err.get('msg')}"}
    )

@app.exception_handler(StarletteHTTPException)
async def custom_http_exception_handler(request: Request, exc: StarletteHTTPException):
    if isinstance(exc.detail, dict) and "code" in exc.detail:
        body = exc.detail
    else:
        body = {"code": "ERROR", "message": str(exc.detail)}
    return JSONResponse(status_code=exc.status_code, content=body, headers=getattr(exc, "headers", None))


# --- Routers ---
app.include_router(clients.router)
app.include_router(rentals.router)

@app.get('/health', response_model=HealthResponse, tags=['System'])
def health_check() -> HealthResponse:

    return HealthResponse(status="ok")