# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-09-22T11:27:16+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import AwareDatetime, BaseModel, EmailStr, Field, conint, constr


class ClientRequest(BaseModel):
    name: constr(min_length=1, max_length=100) = Field(
        ..., description='Nombre del cliente', examples=['Ana Pérez']
    )
    email: EmailStr = Field(
        ..., description='Correo electrónico del cliente', examples=['ana@example.com']
    )


class RentalHistory(BaseModel):
    active: List[int] = Field(
        ..., description='Lista de IDs de arriendos activos', examples=[[1, 3]]
    )
    completed: List[int] = Field(
        ..., description='Lista de IDs de arriendos finalizados', examples=[[2]]
    )
    cancelled: List[int] = Field(
        ..., description='Lista de IDs de arriendos cancelados', examples=[[4]]
    )


class ClientResponse(BaseModel):
    id: conint(le=2147483647) = Field(..., description='ID del cliente', examples=[101])
    name: str = Field(..., description='Nombre del cliente', examples=['Ana Pérez'])
    email: EmailStr = Field(
        ..., description='Correo electrónico del cliente', examples=['ana@example.com']
    )
    createdAt: AwareDatetime = Field(
        ...,
        description='Fecha de creación del cliente',
        examples=['2026-09-16T22:00:00Z'],
    )
    rentalHistory: RentalHistory


class RentalRequest(BaseModel):
    clientId: conint(ge=1, le=2147483647) = Field(
        ..., description='ID del cliente que realiza el arriendo', examples=[101]
    )
    equipmentId: conint(ge=1, le=2147483647) = Field(
        ..., description='ID del equipo a arrendar', examples=[50]
    )
    startDate: AwareDatetime = Field(
        ...,
        description='Fecha de inicio del arriendo',
        examples=['2026-09-20T10:00:00Z'],
    )
    endDate: AwareDatetime = Field(
        ..., description='Fecha de finalización', examples=['2026-09-25T18:00:00Z']
    )


class Status(Enum):
    ACTIVE = 'ACTIVE'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'


class RentalResponse(BaseModel):
    id: conint(le=2147483647) = Field(..., description='ID del arriendo', examples=[1])
    clientId: int = Field(..., description='ID del cliente', examples=[101])
    equipmentId: int = Field(..., description='ID del equipo arrendado', examples=[50])
    startDate: AwareDatetime = Field(
        ...,
        description='Fecha de inicio del arriendo',
        examples=['2026-09-20T10:00:00Z'],
    )
    endDate: AwareDatetime = Field(
        ..., description='Fecha de finalización', examples=['2026-09-25T18:00:00Z']
    )
    status: Status = Field(..., description='Estado del arriendo', examples=['ACTIVE'])


class BadRequestError(BaseModel):
    code: str = Field(..., examples=['BAD_REQUEST'])
    message: str = Field(
        ...,
        examples=[
            'El cuerpo de la solicitud no cumple con las validaciones requeridas.'
        ],
    )


class NotAuthorizedError(BaseModel):
    code: str = Field(..., examples=['UNAUTHORIZED'])
    message: str = Field(
        ..., examples=['Token de autenticación faltante, inválido o expirado.']
    )


class ForbiddenError(BaseModel):
    code: str = Field(..., examples=['FORBIDDEN'])
    message: str = Field(
        ...,
        examples=[
            'El usuario autenticado no posee los permisos necesarios para realizar esta acción.'
        ],
    )


class NotFoundError(BaseModel):
    code: str = Field(..., examples=['RESOURCE_NOT_FOUND'])
    message: str = Field(
        ..., examples=['El recurso solicitado no existe en el sistema.']
    )


class Code(Enum):
    INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK'
    INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION'
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS'


class ConflictError(BaseModel):
    code: Code = Field(
        ...,
        description='Motivo del conflicto:\n- INSUFFICIENT_STOCK: no hay unidades disponibles del equipo (POST /v1/rentals).\n- INVALID_STATE_TRANSITION: el arriendo no está ACTIVE (return y cancel).\n- EMAIL_ALREADY_EXISTS: el email ya está registrado (POST /v1/clients).',
        examples=['INSUFFICIENT_STOCK'],
    )
    message: str = Field(
        ..., examples=['No hay unidades disponibles para el equipo seleccionado.']
    )


class ServiceUnavailableError(BaseModel):
    code: str = Field(..., examples=['EQUIPMENTS_SERVICE_UNAVAILABLE'])
    message: str = Field(
        ...,
        examples=[
            'El servicio gRPC de Equipos no se encuentra disponible momentáneamente.'
        ],
    )


class GatewayTimeoutError(BaseModel):
    code: str = Field(..., examples=['EQUIPMENTS_SERVICE_TIMEOUT'])
    message: str = Field(
        ...,
        examples=[
            'Tiempo de espera agotado al conectar con el servicio gRPC de Equipos.'
        ],
    )


class HealthResponse(BaseModel):
    status: str = Field(..., examples=['ok'])
